In [1]:
#Numpy

In [2]:
import numpy as np
n = np.array([1,2,5,6,7])
type(n)

numpy.ndarray

In [3]:
np.array([1.23,4,6,8.22])

array([1.23, 4.  , 6.  , 8.22])

In [4]:
np.array([1.23,4,6,8.22], dtype="int")

array([1, 4, 6, 8])

In [5]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones(10,dtype="float")

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [8]:
np.arange(0,16,3)

array([ 0,  3,  6,  9, 12, 15])

In [9]:
# ort 10 , standart sapma 4, 3x3

In [10]:
np.random.normal(10,4,(3,3))

array([[11.37001102, 19.76286812,  9.93731304],
       [10.63051996, 15.04422507,  7.9874128 ],
       [ 6.05753697,  7.61318389,  1.24886976]])

In [11]:
a1=np.arange(0,16,3)
a1

array([ 0,  3,  6,  9, 12, 15])

In [12]:
a2=np.full((3,3),1)
a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
#boyut

In [14]:
a1.ndim , a2.ndim

(1, 2)

In [15]:
#size

In [16]:
a1.size , a2.size

(6, 9)

In [17]:
#type

In [18]:
a1.dtype , a2.dtype

(dtype('int32'), dtype('int32'))

In [19]:
#reshape

In [20]:
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
#concte

In [22]:
np.concatenate([a1,a1])

array([ 0,  3,  6,  9, 12, 15,  0,  3,  6,  9, 12, 15])

In [23]:
np.split(a1,2)

[array([0, 3, 6]), array([ 9, 12, 15])]

In [24]:
# array , :1 , 1:3 , 3:

In [25]:
np.split(a1,[1,3])

[array([0]), array([3, 6]), array([ 9, 12, 15])]

In [26]:
np.split(a1,[1,3])[1]

array([3, 6])

In [27]:
np.short(a1)

array([ 0,  3,  6,  9, 12, 15], dtype=int16)

In [28]:
a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
# x>=3,x<=12,size=(dimensions)

In [30]:
a2 = np.random.randint(3,12,size=(4,4))

In [31]:
a2

array([[ 4,  6,  5,  9],
       [ 3, 10,  6,  4],
       [ 9,  8,  6, 11],
       [ 8,  4, 10,  4]])

In [32]:
a2[3,2]

10

In [33]:
a2[:3]

array([[ 4,  6,  5,  9],
       [ 3, 10,  6,  4],
       [ 9,  8,  6, 11]])

In [34]:
#array copy

In [35]:
b2 = a2[:2]
b2

array([[ 4,  6,  5,  9],
       [ 3, 10,  6,  4]])

In [36]:
b2[0,0]

4

In [37]:
b2[0,0]= 101
b2

array([[101,   6,   5,   9],
       [  3,  10,   6,   4]])

In [38]:
a2

array([[101,   6,   5,   9],
       [  3,  10,   6,   4],
       [  9,   8,   6,  11],
       [  8,   4,  10,   4]])

In [39]:
c2 = a2[:2].copy()
c2

array([[101,   6,   5,   9],
       [  3,  10,   6,   4]])

In [40]:
c2[0,0]=303
c2

array([[303,   6,   5,   9],
       [  3,  10,   6,   4]])

In [41]:
a2

array([[101,   6,   5,   9],
       [  3,  10,   6,   4],
       [  9,   8,   6,  11],
       [  8,   4,  10,   4]])

In [42]:
#Fancy Index

In [43]:
a1

array([ 0,  3,  6,  9, 12, 15])

In [44]:
a1[a1>5]

array([ 6,  9, 12, 15])

In [45]:
ind=[0,1,2]
a1[ind]

array([0, 3, 6])

In [46]:
l1=[a1[0],a1[2],a1[1],a1[3]]

In [47]:
l1


[0, 6, 3, 9]

In [48]:
type(l1)

list

In [49]:
#Combined Indexing

In [50]:
a2

array([[101,   6,   5,   9],
       [  3,  10,   6,   4],
       [  9,   8,   6,  11],
       [  8,   4,  10,   4]])

In [51]:
# a2 row 1 col 1 ,0 ,3

In [52]:
a2[1,[1,0,3]]

array([10,  3,  4])